<?php

/**
 * Created by PhpStorm.
 * User: bbdnet1571
 * Date: 2017/03/24
 * Time: 5:42 PM
 */
class user extends user_management
{
   private $username;
   private $password;
   private $email;
   private $first_name;
   private $last_name;
   private $biography;
   private $age;

	/**
	 * user constructor.
	 */
	public function __construct()
   {
   	   $this->username = $_POST['username'];
	   $this->password = $this->password_hashing($_POST['username']);
	   $this->email = $_POST['email'];
	   $this->first_name = $_POST['firstname'];
	   $this->last_name = $_POST['lastname'];
	   $this->biography = $_POST['bio'];
	   $this->age = $_POST['age'];
   }


	/** @noinspection PhpSignatureMismatchDuringInheritanceInspection */
    public function create_user() {
            parent::create_user( $this->username, $this->password, $this->first_name, $this->last_name,
                                   $this->biography, $this->email, $this->age);
   }

   public function update_user()
   {
	   parent::update_user(); // TODO: Change the autogenerated stub
   }


	/**
    * @param $not_hashed_password : the password that is not hashed
    * @return string : the hashed password
    */
   private function password_hashing($not_hashed_password)
   {
       $hash = array();
       $not_hashed_password = str_split($not_hashed_password);
       foreach($not_hashed_password as $value) {
           $value = hash("md5", $value);
           array_push($hash, $value);
       }
       $hashed_password = implode("" ,$hash);
       $hashed_password = hash("whirlpool", $hashed_password);
       return($hashed_password);
   }

}